name: Build Resume Releases
run-name: "Building and uploading release pdf and html documents."

permissions:
  contents: write

on:
  push:
    tags:
      - "v*"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Install Panodoc
        run: sudo apt-get install pandoc
        
      - name: Install wkhtmltopdf
        run: sudo apt-get install wkhtmltopdf

      - name: Build Resume
        run: make all

      - name: Rename pdf built resume
        run: mv ./build/bnarin_resume.pdf ./build/bnarin_resume${{ github.ref_name }}.pdf
      
      - name: Rename html built resume
        run: mv ./build/bnarin_resume.html ./build/bnarin_resume${{ github.ref_name }}.html

      - name: Create Release and Upload Files
        uses: softprops/action-gh-release@v0.1.15
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            build/bnarin_resume_${{ github.ref_name }}.html
            build/bnarin_resume_${{ github.ref_name }}.pdf

  
